# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "2"]
    end
      ubuntu.vm.box = "ubuntu/focal64"
      ubuntu.vm.network "public_network", ip: "192.168.0.220"
      ubuntu.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y && sudo apt install neofetch -y"
  end
  config.vm.define "debian11" do |debian11|
      config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "2"]
      end
      debian11.vm.box ="generic/debian11"
      debian11.vm.network "public_network", ip: "192.168.0.221"
      debian11.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y && sudo apt install neofetch -y"
  end
  config.vm.define "rhel8" do |rhel8|
      config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024", "--cpus", "2"]
      end
      centos8.vm.box ="generic/rhel8"
      centos8.vm.network "public_network", ip: "192.168.0.222"
      centos8.vm.provision "shell", inline: "sudo dnf update -y && sudo dnf upgrade -y"
  end
end
