# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
  config.vm.synced_folder "./", "/vagrant"
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "512", "--cpus", "4"]
    end
      ubuntu.vm.box = "ubuntu/focal64"
      ubuntu.vm.network "public_network", ip: "192.168.0.220"
      ubuntu.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y"
    end
end
