# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel8"
  config.vm.network "public_network", ip: "192.168.0.222"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 4
  end

end
